### PR TITLE
Update Dialog System with Modular Support

### PR DESCRIPTION
**Pull request by atrblizzard**
- Dialog system now updated to use develop branch
- Added support to play dialog audio, including editor util for preview
- Overhauled the interface for the dialog nodes
- Replaced BaseDialogNode variables (old values are kept through FormerlySerializedAs)

### CODE REVIEW

**Comment by Seneral** [comment]
Hey, good to see you're keeping it up to date:)
Can merge it anytime you want. Also will message Baste so he can give you access so you don't need to wait for me lol

**Comment by atrblizzard** [comment]
Awesome, appreciate it! I'll try my best to keep updating the dialog system where it's suitable.
Right now it'll require develop branch, but can definitely be merged so we can have an updated base to work with. :)

**Comment by Baste-RainGames** [comment]
@Seneral, can't you give them access? It's under Settings/Collaborators.

If not, I'll fix it, no problem.

**Comment by Seneral** [comment]
@Baste-RainGames I have no access to the settings for some reason, but now that you mention it, I should be, right? Maybe you changed a settings somewhere? Didn't bother me until now, but would be nice to maintain this framework without depending on one person;)

**Comment by Baste-RainGames** [comment]
Looking into it, it seems like I have to transfer the ownership of the repo to you to make that work.

That'd probably be the ideal solution. Is that fine with you?

**Comment by Seneral** [comment]
Would be best indeed, but I'm unsure in regards to links. Seems like the repo link would redirect automatically but the gh-pages (documentation) link will change without a redirect...
Anyway, would be best in the long run for both of us:) Thank you so much for creating this repo in the first place though! ;)

**Comment by Seneral** [comment]
@atrblizzard Alright, repo transferred and you should be a collaborator now:)

**Comment by Seneral** [comment]
Any news? Else I'll merge in a few days:)

**Comment by atrblizzard** [comment]
Sorry about that, I swear I thought it was already commited! Should have the new commits ready soon enough :)

**Comment by Seneral** [comment]
No problem! :) Glad you've not abandoned it;)

**Pull request merged**
